name :MY-REACT-APP-CI

on:
  push:
    branches:['master']
  pull:
    branches:["master"]



 jobs:
  build:
    run-on:ubuntu-latest


    steps:
      -name:Checkout code
      uses:action/checkout@v4


       - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

     
      - name: Install dependencies
        run: npm install

     
      - name: Build project
        run: npm run build

     
      - name: Run tests
        run: npm test
        continue-on-error: true   # won’t fail if no test     